### PR TITLE
[cmake] Rename find_package(kodi) to Kodi

### PR DESCRIPTION
**Pull request by hudokkow**
Needed after https://github.com/xbmc/xbmc/pull/9750 goes in

### CODE REVIEW

**Comment by hudokkow** [comment]
@garbear, jenkins is failing on Android, RBPi and Linux with
> /home/jenkins/workspace/Android-X86/tools/depends/target/binary-addons/i686-linux-android-android-17/build/peripheral.joystick/src/utils/StringUtils.cpp: In static member function 'static std::string& JOYSTICK::StringUtils::RemoveMACAddress(std::string&)':
/home/jenkins/workspace/Android-X86/tools/depends/target/binary-addons/i686-linux-android-android-17/build/peripheral.joystick/src/utils/StringUtils.cpp:74:40: error: no matching function for call to 'regex_replace(std::string&, std::regex&, const char [1])'
   str = std::regex_replace(str, mac, "");
                                        ^

Build log: http://jenkins.kodi.tv/job/BuildMultiWithAddons-PR/8/
Linux full log: http://jenkins.kodi.tv/job/LINUX-64/7904/consoleFull

**Comment by garbear** [comment]
#41 should fix the build

**Comment by garbear** [comment]
@hudokkow I merged #41, are those platforms fixed?

**Comment by hudokkow** [comment]
I'll check later with jenkins. Thanks.

**Pull request merged**
