### PR TITLE
Added/updated more button maps

### PR DESCRIPTION
**Pull request by pcuttle**
Added 2x button maps for directinput, updated 2x button maps for directinput, added 1x button map for linux

I had to manually add some of the mappings as the right-axes were not mapping properly in Windows 10.

### CODE REVIEW

**Comment by garbear** [comment]
Thanks. Do you have an XInput (360-style) controller you can test with? just to verify that it's a DirectInput problem

I've got Kodi and peripheral.joystick running in a debugger now, I'll see if I can reproduce

**Comment by garbear** [comment]
Can you prefix your commit with a [] tag so it stands out easier in a commit list? I use `[buttonmaps]` as you can see [here](https://github.com/kodi-game/peripheral.joystick/commits/master).

**Comment by pcuttle** [comment]
I can use the prefixes for future commits, unless you want me to try and amend the message?

I will run it up myself in the VS debugger hopefully next weekend, and also try and acquire a XInput controller from somewhere.

**Comment by a1rwulf** [comment]
If it's already merged, no need to amend - actually it's a must not in this case :)

**Comment by garbear** [comment]
@pcuttle, because you're awesome and helped out with button maps, I was wondering if you could remap any controllers that have analog triggers? I've added a [configuration](https://github.com/kodi-game/peripheral.joystick/blob/retroplayer/peripheral.joystick/resources/buttonmaps/xml/cocoa/Wireless_360_Controller_v045E_p028E_15b_6a.xml#L4-L7) section to the button maps because I'm trying to track down which platforms have triggers that aren't centered about zero.

**Comment by pcuttle** [comment]
@garbear Unfortunately none of my controllers have analog triggers, only analog sticks.  Would you still like me to remap them anyway?

**Comment by garbear** [comment]
I added a udev driver on linux for rumble, so you'll need to remap linux eventually. You can send that one whenever you upgrade to the udev driver.

**Comment by pcuttle** [comment]
Is there a linux test build, or do I need to compile it? I used OpenELEC/LibreELEC to do the mappings before, but it doesn't look like there is a build yet that includes the udev update.

**Comment by pcuttle** [comment]
@garbear I am still having an issue with mapping my Logitech Rumblepad 2 in Windows 10.  The right-analog-stick up/down never register as inputs in Kodi, although they work fine in Windows.
http://pastebin.com/jC2sRw1w

**Comment by garbear** [comment]
Can you give the latest retroplayer branches a try? I pushed a change that might fix this, but even if not the improved logging will help us track this down.

**Pull request merged**
